# Generated by Django 5.2.6 on 2025-09-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_country_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationtoken',
            old_name='customer',
            new_name='customuser',
        ),
    ]
