# Generated by Django 5.2.6 on 2025-10-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciever',
            new_name='reciepient',
        ),
    ]
