# Generated by Django 5.2.6 on 2025-10-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_reciever_notification_reciepient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciepient',
            new_name='recipient',
        ),
    ]
