# Generated by Django 5.2.6 on 2025-09-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='creator',
            new_name='user',
        ),
    ]
